const actionTypes = {
  SHOW_LOADER: 'SHOW_LOADER',
  HIDE_LOADER: 'HIDE_LOADER',
  RESULT_SAVED: 'RESULT_SAVED',
  RESULT_DELETED: 'RESULT_DELETED',
  TOGGLE_EDIT_ROW: 'TOGGLE_EDIT_ROW',
  OPEN_EXAMINATION_RESULT_EDITOR: 'OPEN_EXAMINATION_RESULT_EDITOR',
};

export default actionTypes;
