linters:
  LineLength:
    max: 120
    severity: error

  Indentation:
    character: space
    width: 2
    severity: error

  FinalNewline:
    enabled: true
    severity: error

exclude:
  - '.history/**/*'
