# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

plugins:
  - rubocop-performance
  - rubocop-rspec_rails
  - rubocop-packaging
  - rubocop-thread_safety
  - rubocop-capybara
  - rubocop-erb
  - rubocop-haml
  - rubocop-rails

AllCops:
  NewCops: enable
  Include:
    - '**/*.rb'
    - '**/config.ru'
    - '**/*.haml'
    - '**/*.html.haml.erb'
    - '**/*.erb'
  Exclude:
    - 'Rakefile'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'lib/tasks/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'client/node_modules/**/*'
    - 'bin/**/*'
    - 'bundler_stubs/**/*'
    - 'config/locales/plurals.rb'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'app/javascript/**/*'
    - 'app/assets/**/*'
    - 'app/frontend/**/*'
    - '**/*.js'
    - '**/*.jsx'
    - '**/*.json'
    - '**/*.scss'

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/ModuleLength:
  Max: 300

Metrics/ParameterLists:
  Max: 10

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/FileName:
  Exclude:
    - Capfile
    - Gemfile

Bundler/DuplicatedGem:
  Enabled: true
Bundler/InsecureProtocolSource:
  Enabled: true
Bundler/OrderedGems:
  Enabled: true
Gemspec/OrderedDependencies:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateCaseCondition:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/DuplicateHashKey:
  Enabled: true
Lint/DuplicateMagicComment:
  Enabled: true
Lint/DuplicateMatchPattern:
  Enabled: true
Lint/DuplicateMethods:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/DuplicateRequire:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/DuplicateSetElement:
  Enabled: true
Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Style/AccessModifierDeclarations:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/AmbiguousEndlessMethodDefinition:
  Enabled: true
Style/AsciiComments:
  Enabled: true
Style/SingleLineBlockParams:
  Enabled: true
Style/SingleLineDoEndBlock:
  Enabled: true
Style/SingleLineMethods:
  Enabled: true
