version: "3.9"

services:
  db:
    container_name: db
    image: postgres:17.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:8.0.2-alpine
    command: ['redis-server', '--appendonly', 'yes']
    entrypoint:
      - sh
      - -lc
      - |
        chown -R redis:redis /data
        exec redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/akadem_students/Dockerfile
      target: production
    image: vedic_crm:prod
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      SECRET_KEY_BASE: "<ваш_секрет>"
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis
    working_dir: /app
    # ENTRYPOINT in the Dockerfile will automatically execute:
    # bundle exec rails db:create db:migrate && bundle exec puma -C config/puma.rb

volumes:
  db_data:
  redis_data: