services:
  db:
    restart: unless-stopped
    image: vedic_academy_db:latest
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - '5432:5432'

  redis:
    image: redis:8.0.2-alpine
    platform: linux/amd64
    command: sh -lc "chown -R redis:redis /data && exec redis-server --appendonly yes"
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  web:
    image: vedic_academy_lms:latest
    platform: linux/amd64
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    ports:
      - '3000:3000' # Rails
      - '3036:3036' # Vite Dev Server
      - '3037:3037' # Vite test
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis

volumes:
  db_data:
  redis_data:
  docker_sock:
