const actionTypes = {
  SHOW_LOADER: 'SHOW_LOADER',
  HIDE_LOADER: 'HIDE_LOADER',
  NEXT_PERSON: 'NEXT_PERSON',
  MARK_UNKNOWN: 'MARK_UNKNOWN',
  MARK_PRESENCE: 'MARK_PRESENCE',
  PREVIOUS_PERSON: 'PREVIOUS_PERSON',
  OPEN_ATTENDANCE_SUBMITTER: 'OPEN_ATTENDANCE_SUBMITTER',
  UPDATE_CLASS_SCHEDULES_AND_PAGE: 'UPDATE_CLASS_SCHEDULES_AND_PAGE',
};

export default actionTypes;
