name: GitHub Metrics

on:
  push:
    branches: [main]
    paths-ignore:
      - 'coverage/**'

jobs:
  github-metrics:
    if: github.actor != 'coveralls' && github.event.head_commit.message != 'coverage data'
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: 'header, activity, community'
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 8
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
