name: GitHub Metrics

on:
  push:
    branches: [main]

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.svg
          token: ${{ github.token }}
          committer_token: ${{ github.token }}
          output_action: commit
          committer_branch: metrics
          base: 'header, activity, community'
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 8
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
